
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  build:
    name:     "v2panel"
    arch:     "386"
    system:   "linux,windows"
    mod:      "none"
    packSrc:  "resource,manifest"
    version:  "v1.0.0"
    output:   "./bin"
    extra:    ""
  gen:
    dao:
    - link:     "mysql:root:12345678@tcp(127.0.0.1:3306)/gov2panel"
      tables:   "v2_user,v2_plan,v2_coupon,v2_coupon_use,v2_recharge_records,v2_ticket,v2_invitation_records,v2_payment,v2_proxy_service,v2_server_route"
      jsonCase: "Snake"
